spring.application.name=parksaathi
# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/parksaathi
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update      # use 'validate' or 'none' in prod
spring.jpa.show-sql=true