server.port=8080
spring.application.name=parksaathi
# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/parksaathi_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# use 'validate' or 'none' in prod
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIHBhcmtzYWF0aGkgand0IHRva2VuIGdlbmVyYXRpb24=
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# OTP
otp.expiration-seconds=300
otp.length=6
# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} [DEVICE:%X{x-parksaathi-device}] [CORRELATIONID:%X{x-parksaathi-correlation-id}] - %msg%n
